modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "retrotweaks"
version = "${version}"
displayName = "RetroTweaks"
authors = ["PoeticRainbow", "GameMasterPDX"]
description = '''
Implements visual tweaks to send your Minecraft back in time!
'''
logoFile = "assets/retrotweaks/icon.png"

[[dependencies.retrotweaks]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.retrotweaks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.retrotweaks]]
modId = "architectury"
type = "required"
versionRange = "[19.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "retrotweaks-required.mixins.json"

[[mixins]]
config = "retrotweaks-tweak.mixins.json"

[[mixins]]
config = "retrotweaks-client-required.mixins.json"

[[mixins]]
config = "retrotweaks-client-tweak.mixins.json"

[[mixins]]
config = "retrotweaks-neoforge-client-tweak.mixins.json"
