name: Build
on:
  push:
    branches:
      - version/26.1.2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Upload Fabric Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fabric-artifacts
          path: "fabric/build/libs/"
      - name: Upload NeoForge Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: neoforge-artifacts
          path: "neoforge/build/libs/"